//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_PTLStaff_Confirmation_Audit> t_PTLStaff_Confirmation_Audit { get; set; }
        public virtual DbSet<t_PTLStaff_Details> t_PTLStaff_Details { get; set; }
        public virtual DbSet<t_PTLStaff_Master_Data> t_PTLStaff_Master_Data { get; set; }
        public virtual DbSet<t_PTLStaff_Master_DataCodes> t_PTLStaff_Master_DataCodes { get; set; }
        public virtual DbSet<t_PTLStaff_Master_UserSites> t_PTLStaff_Master_UserSites { get; set; }
        public virtual DbSet<t_PTLStaff_Submit_Details> t_PTLStaff_Submit_Details { get; set; }
        public virtual DbSet<v_Hovis_Calendar> v_Hovis_Calendar { get; set; }
        public virtual DbSet<v_PTLStaff_MasterData_Breaks> v_PTLStaff_MasterData_Breaks { get; set; }
        public virtual DbSet<v_PTLStaff_MasterData_Discipline> v_PTLStaff_MasterData_Discipline { get; set; }
        public virtual DbSet<v_PTLStaff_MasterData_Plants> v_PTLStaff_MasterData_Plants { get; set; }
        public virtual DbSet<v_PTLStaff_MasterData_Reason> v_PTLStaff_MasterData_Reason { get; set; }
        public virtual DbSet<v_PTLStaff_MasterData_Shifts> v_PTLStaff_MasterData_Shifts { get; set; }
    }
}
