//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PTLStaff_Master_DataCodes
    {
        public t_PTLStaff_Master_DataCodes()
        {
            this.t_PTLStaff_Master_Data = new HashSet<t_PTLStaff_Master_Data>();
        }
    
        public string DataCode { get; set; }
    
        public virtual ICollection<t_PTLStaff_Master_Data> t_PTLStaff_Master_Data { get; set; }
    }
}
