//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PTLStaff_Master_Data
    {
        public long Recid { get; set; }
        public string DataCode { get; set; }
        public string DataValue { get; set; }
    
        public virtual t_PTLStaff_Master_DataCodes t_PTLStaff_Master_DataCodes { get; set; }
    }
}
