//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PTLStaff_Master_UserSites
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserSiteCode { get; set; }
    
        public virtual v_PTLStaff_MasterData_Plants v_PTLStaff_MasterData_Plants { get; set; }
    }
}
