//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PTLStaff_Details
    {
        public long Recid { get; set; }
        public string StatusCode { get; set; }
        public string SiteCode { get; set; }
        public string PTLUserName { get; set; }
        public string PTLSAPName { get; set; }
        public string PTLUserID { get; set; }
        public string SchedShiftDuration { get; set; }
        public string RevisedShiftDuration { get; set; }
        public string ScheduledBreaks { get; set; }
        public string RevisedBreaks { get; set; }
        public string ReasonForChangeInShiftLength { get; set; }
        public string Comments { get; set; }
        public string DisiplinaryStage { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public string Confirmed { get; set; }
    
        public virtual v_PTLStaff_MasterData_Plants v_PTLStaff_MasterData_Plants { get; set; }
        public virtual v_PTLStaff_MasterData_Breaks v_PTLStaff_MasterData_Breaks { get; set; }
        public virtual v_PTLStaff_MasterData_Breaks v_PTLStaff_MasterData_Breaks1 { get; set; }
        public virtual v_PTLStaff_MasterData_Reason v_PTLStaff_MasterData_Reason { get; set; }
        public virtual v_PTLStaff_MasterData_Discipline v_PTLStaff_MasterData_Discipline { get; set; }
        public virtual v_PTLStaff_MasterData_Shifts v_PTLStaff_MasterData_Shifts { get; set; }
        public virtual v_PTLStaff_MasterData_Shifts v_PTLStaff_MasterData_Shifts1 { get; set; }
    }
}
