//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Hovis_Calendar
    {
        public System.DateTime CalendarDate { get; set; }
        public string CalendarDateChar { get; set; }
        public short FinancialYear { get; set; }
        public short FinancialQtr { get; set; }
        public short FinancialPeriod { get; set; }
        public short FinancialWeek { get; set; }
    }
}
