//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffShifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PTLStaff_MasterData_Breaks
    {
        public v_PTLStaff_MasterData_Breaks()
        {
            this.t_PTLStaff_Details = new HashSet<t_PTLStaff_Details>();
            this.t_PTLStaff_Details1 = new HashSet<t_PTLStaff_Details>();
        }
    
        public long Recid { get; set; }
        public string DataCode { get; set; }
        public string DataValue { get; set; }
    
        public virtual ICollection<t_PTLStaff_Details> t_PTLStaff_Details { get; set; }
        public virtual ICollection<t_PTLStaff_Details> t_PTLStaff_Details1 { get; set; }
    }
}
